export enum MutationTypes {
  SET_COMMENT = 'SET_COMMENT',
  UPDATE_COMMENTS_LIST = 'UPDATE_COMMENTS_LIST',
  UNSHIFT_COMMENTS_LIST = 'UNSHIFT_COMMENTS_LIST',
  DELETE_COMMENT = 'DELETE_COMMENT',
  UPDATE_RATING = 'UPDATE_RATING',
  RESET_COMMENT_FORM = 'RESET_COMMENT_FORM',
  RESET_COMMENTS_LIST = 'RESET_COMMENTS_LIST',
  SET_RATING = 'SET_RATING',
  SET_LOADING = 'SET_LOADING'
}
